# Generated by Django 4.2.27 on 2026-01-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(help_text="e.g., '2 cups', '500g', '1 tablespoon'", max_length=50)),
            ],
        ),
    ]
