# Generated by Django 4.2.27 on 2026-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_pics/'),
        ),
    ]
